@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.silentchaos512.mechanisms.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;