@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.silentchaos512.mechanisms.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;