@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.mechanisms.init;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;