@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.mechanisms.block.electricfurnace;

import mezz.jei.api.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;