@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.mechanisms.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;