@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.mechanisms.compat.jei;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;