@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.silentchaos512.mechanisms.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;