@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.mechanisms.block.alloysmelter;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;