@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.silentchaos512.mechanisms.common.blocks.generators.coalgenerator;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;